package org.pixeltime.enchantmentsenhance.manager;

import org.pixeltime.enchantmentsenhance.Main;
import org.pixeltime.enchantmentsenhance.event.enchantment.*;
import org.pixeltime.enchantmentsenhance.listener.ArmorHandler;

public class EnchantmentsManager {
    public void setUp() {
        Main.getMain().getServer().getPluginManager().registerEvents(new ArmorHandler(null), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Assassin(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Batvision(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Blessed(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Demonic_Aura(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Dodge(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Hex(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Jump(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Kill_Confirm(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Lifesteal(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Speed(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Zeus(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Snare(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Execute(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Crushing(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Aegis(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Stealth(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Purge(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Divine(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Platemail(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Turmoil(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Spiked(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Flame_Cloak(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Entangle(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Corruption(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Battlecry(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Pyromaniac(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Holy_Smite(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Riftslayer(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Curse(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Eyepatch(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Mischief(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Plunder(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Shadowstep(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Tamer(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Wolves(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Repel(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Swimmer(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Medic(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Reborn(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Health_Boost(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Endless(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Molten(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Immolation(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Strength(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Horse_Rider(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Petrify(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Thief(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Demon_Siphon(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Web_Trap(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Paralyze(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Soft_Touch(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Tnt_Shooter(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Rekt(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Reinforced(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Wild_Mark(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Shearer(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Farmer(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Haste(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Lumberjack(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Plow(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Smelt(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Auto_Block(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Shooter(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Feather_Fall(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Suicide(), Main.getMain());
        Main.getMain().getServer().getPluginManager().registerEvents(new Launch(), Main.getMain());
    }
}
