SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE IF NOT EXISTS `enchantmentsenhance` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `playername` VARCHAR(256) NOT NULL UNIQUE,
  `failstack` INT NOT NULL DEFAULT 0,
  `items` VARCHAR(256) NOT NULL,
  `valks` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`playername`)
)

  ENGINE =InnoDB
  DEFAULT CHARSET =latin1;

