SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

CREATE TABLE IF NOT EXISTS `enchantmentsenhance` (
  `id` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `playername` VARCHAR(255) NOT NULL UNIQUE,
  `failstack` INT(6) NOT NULL DEFAULT 0,
  `items` VARCHAR(255) NOT NULL,
  `valks` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY (`playername`)
)

  ENGINE =InnoDB
  DEFAULT CHARSET =latin1;

